In [ ]:
print("gauri kothekar")

gauri kothekar


In [ ]:
str1="gauri"
x=20
print( x * str1) #static loop

gaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigaurigauri


# `**5** **june** **2023**`

In [ ]:
num1=100
num1=200
print(num1)

200


In [ ]:
str="abcdef"
print(str[-1])
print(str[1])
print(str[:])
print(str[::])
print(str[:-1])
print(str[::-1])
print(str[2:-1])
print(str[-1:])

f
b
abcdef
abcdef
abcde
fedcba
cde
f


In [ ]:
del str[1]
print(str)


TypeError: ignored

In [ ]:
str1=str.upper()
print(str1)

In [ ]:
print(str.lower())

In [ ]:
list1 = ['a','b','c','d','e']
print(list1)

In [ ]:
list1.append('gauri')
print(list1)

In [ ]:
list1.extend("ab")
print(list1)

In [ ]:
list1.insert(2 ,'kothekar')
print(list1)

In [ ]:
list1.pop()
print(list1)

In [ ]:
list1.pop(5)
print(list1)

In [ ]:
list1.remove("kothekar")
print(list1)

In [ ]:
list1.clear()
print(list1)

In [ ]:
del list1


In [ ]:
print(list1)

# **6 june 2023**

In [ ]:
#tuple creation
tup=(1,2,3)
print(tup[1])
# print(tup.index(1))

In [ ]:
tup1=(2,4,5)
tup2=(4,7,8)
print(tup1+tup2) #concatenation


In [ ]:
#methods index and count

print(tup1[1])


tup3=(2,3,3,3,3,4)
print(tup3.count(3))
print(tup3.index(3))

In [ ]:
#tuple inside list
li=[(2,4),5]
print(li[0][1])

In [ ]:
#list inside tuple
tupp=([1,2,3,4],7)
print(tupp[0])
print(tupp.count(7))

In [ ]:
tup4 = ()
tup5=(50)
print(tup4+tup5)

In [ ]:
tup4 = ()
tup5=(50,)
print(tup4+tup5)

In [ ]:
dic1={1:2,3:5 ,"x":"y"}
print(dic1[3])      # no indexing , it is done by key


In [ ]:
#add method
dic1={1:2,3:5 ,"x":"y"}
print(dic1.update({"gauri":"kothekar"}))



In [ ]:
dic1={1:2,3:5 ,"x":"y"}
dic1.update({"gauri":"kothekar"}) #add ke liye update
print(dic1)

In [ ]:
# update
dic1[3]="gauri"
print(dic1)

In [ ]:
# remove

dic1.pop(1) #pop with key
print(dic1)

In [ ]:
dic1.popitem()
print(dic1)

In [ ]:
#clear and del

In [ ]:
print(dic1.keys()) #stored in the form of list

In [ ]:
print(dic1.values())   #stored in the form of list

In [ ]:
set1={1,2,3,4,5}
print(set)

In [ ]:
#methods

#add and remove
set1.add(6)
print(set1)



In [ ]:
set1.remove(4)
print(set1)

In [ ]:
set1={1,2,3,4,5}
set2={6,7,8,9,0}
print(set1.union(set2))


In [ ]:
set1={1,2,3,4,5}
set2={6,7,8,9,0}
print(set1.intersection(set2))

In [ ]:
set1={1,2,3,4,5}
set2={6,7,8,9,0}
print(set1.difference(set2))

In [ ]:
set1={1,2,3,4,5}
set2={6,7,8,9,0}
print(set1.symmetric_difference(set2))

In [ ]:
print(set1 | set2)
print(set1 & set2)
print(set1 - set2)
print(set1 ^ set2)

In [ ]:
#control statements

#if....
x=5
if x==5:
  print("the number matches")

In [ ]:
x,y=5,6
if x<y:
  print("x is lesser")
else:
  print("x is greater")

In [ ]:
x,y,z=5,6,7
if x<y:
  print("x is smallest")
elif x>y:
  print(" x is larger")
else:
  print(" y is largest")


In [ ]:
x=20
if x%3==0:
  if x%5==0:
    print("it is divisible by both")
  else:
    print("5 se nahi")
else:
  print(" nhi")

In [ ]:
x=[1,2,3,4,5]
for i in x:
  print(i)

In [ ]:
for i in range(0,15):
  print(i*i)

In [ ]:
x=10
i=0
while(i<x):
  print("hello itm")
  i=i+1


In [ ]:
x=10
i=0
while(i<x):
  print("hello itm")
  i=i+1
  break

In [ ]:
i=0
n=10
while i<n:
  i=i+1
  if i==6:
    continue
  print(i)

In [ ]:
#for....else

li=[1,2,3,4]
for i in li:
  if i==2:
    print(i)
else:
  print("hy")

In [ ]:
#for ....while
li1=[1,2,3,4]
while li1:
  print(li1)


else:
  print("bye")


In [ ]:
#list comprehension

list1=[x for x in range (0 , 10)]
print(list1)

In [ ]:
list2=[x  * x for x in range(0,10)]
print(list2)


In [ ]:
# dictionary comprehension

list3={x: x*x for x in range(0,20)}
print(list3)

In [ ]:
# zip function

li1=[1,2,3,4,5]
li2=[2,3,4,5,6]
for i in zip(li1,li2):
  print(i)

In [ ]:
li1=[1,2,3,4,5]
li2=[2,3,4,5,6]

for i_li1 , i_li2 in zip(li1,li2):
  print(i_li1,i_li2)

**`7 june 2023`**



In [ ]:
def foo(x):
  print(x)

foo(5)

In [ ]:
def foo(x,y):
  print( x+y)


foo(4,5)

In [ ]:
#creating tuple and multiple values can be stored

def foo(*num):
  print(num)



foo(10,20,40,50)

In [ ]:
def foo(**num):
  print(num)


foo(hy ="gauri")

In [ ]:
def foo():
  print("gauri")

print(foo())

In [ ]:
def big(a,b):
  res=a+b
  return res

  def small():
    rsqr=res**2
    return rsqr
  return small

print(big(10,20))


In [ ]:
def big(a,b):
  res=a+b

  def small():
    rsqr=res**2
    return rsqr
  return small

print(big(10,20))

In [ ]:
def big(a,b):
  res=a+b

  def small():
    rsqr=res**2
    return rsqr
  return small()

print(big(10,20))

In [ ]:
def big(a,b):
  res=a+b
  yield res

  def small():
    rsqr=res**2
    return rsqr
  return small()

print(big(10,20))

In [ ]:
# decorator
# allows you to modify the functionality of function.it wraps inside .
#In Python, a decorator is a design pattern that allows you to modify the functionality of a function by wrapping it in another function.

# The outer function is called the decorator, which takes the original function as an argument and returns a modified version of it.

def outer(x):
  def inner(y):
    return y+y
  return inner

valu1=outer(5)
value=valu1(6)
print(value)




In [ ]:
# decorator
# allows you to modify the functionality of function.it wraps inside .
#In Python, a decorator is a design pattern that allows you to modify the functionality of a function by wrapping it in another function.

# The outer function is called the decorator, which takes the original function as an argument and returns a modified version of it.

def outer(x):
  def inner():
    return x+x
  return inner

valu1=outer(5)
value=valu1()
print(value)




In [ ]:
def hello():
    def hi():
        print("Hello")
    return hi
new = hello()
new()

In [ ]:
#iterator

mytuple = [1,2,3,4,5]
my = iter(mytuple)
# print(my)
# print(next(my))
for i in my:
  print(i)

In [ ]:
def table(num):
  w=iter(num)
  return w


table("hi")



In [ ]:
def table(num):
  w=iter(num)

  for i in w:
    print(i)

table("gauri")

In [ ]:
def table(num):
  # w=iter(num)

  for i in iter(range(num)):
    print(i)

table(20)

In [ ]:
def myname(func):
  print("gauri")
  def mysurname():
    print("kothekar")
  return mysurname


@myname

def daily_backup():
  print('Daily backup job has finished.')


daily_backup()




In [ ]:
def myname(func):
  print("gauri")
  func()
  def mysurname():
    print("kothekar")
    func()
  return mysurname


@myname

def daily_backup():
  print('Daily backup job has finished.')


daily_backup()

In [ ]:
def gen_func(x,y):
  z=x+y
  return z

gen_func(2,5)

In [ ]:
# #The yield keyword in Python is similar to a return statement used for returning values in Python which returns a generator object to the one who calls the function which contains yield, instead of simply returning a value. The main difference between them is, the return statement terminates the execution of the function. Whereas, the yield statement only pauses the execution of the function. Another difference is return statements are never executed. whereas, yield statements are executed when the function resumes its execution.

# Advantages of yield:

# Using yield keyword is highly memory efficient, since the execution happens only when the caller iterates over the object.
# As the variables states are saved, we can pause and resume from the same point, thus saving time.
# Disadvantages of yield:

# Sometimes it becomes hard to understand the flow of code due to multiple times of value return from the function generator.
# Calling of generator functions must be handled properly, else might cause errors in program



def gen_func(x,y):
  yield x+y  #uses iterator


# gen_func(2,4)

for i in gen_func(4,7):
  print(i)

print(next(gen_func(2,4)))


In [ ]:

def gen_func(x,y):
  yield x+y  #uses iterator
  return x+y


# gen_func(2,4)

for i in gen_func(4,7):
  print(i)

print(next(gen_func(2,4)))

o=gen_func(4,5)
y=o()
print(y)

In [ ]:
def add(x,y):
  yield x+y  #uses iterator yield makes int interator

def sub(x,y):
  return x-y

print(next(add(5,2)))
# print(next(sub(5,2)))
sub(5,2)

In [ ]:
def gauri(x,y):
  yield x+y

k=gauri(5,4)
print(next(k))

In [ ]:
def even(func):
  print("number is even")
  func()
  def odd():
    print("number is odd")
    func()
  return odd

@even
def natural():
  print("it is also natural")



natural()




In [ ]:
def girl():
  print("she is pretty")
  def boy(func):
    print("he is handsome")
    func()
  return boy

@boy
def gender():
  print("it includes both")

gender()

In [ ]:
def girl(func):
  print("she is pretty")
  func()
  def boy():
    print("he is handsome")
    func()
  return boy

@girl

def gender():
  print("also smarter")


gender()

In [ ]:
def start_roll(func):
  def end_roll():
    for i in range(2000,2006):
       func()
       print("betn1cs",i)
  return end_roll


@start_roll

def common():
  print("itm university")

common()


In [ ]:
dic={2:2,4:5}

x=iter(dic)
print((next(x)))
print((next(x)))

In [ ]:
li=[1,2,3,4,5]
x=iter(li)
# print(next(x))
for i in x:
  print(i)

In [ ]:
string="gauri"
x=iter(string)
for i in x:
  print(i)

In [ ]:
tup=(1,2,3)
x=iter(tup)
for i in x:
  print(i)

8 june 2023

In [ ]:
#class

class DemoClass:
  var = 10


value = DemoClass()
print(value.var)

In [ ]:
class Student:
  def roll(self):
    print("these are engineers")


object = Student()
object.roll()


In [ ]:
class Btech:
  def cse(self):
    print("computer science")

  def civil(self):
    print("these are like architect")


object =Btech()
object.cse()
object.civil()




In [ ]:
class University:
  def government(self):
    print("top ")

  def autonomous(self):
    print("average")


object1=University()
object1.government()

In [ ]:
class MyClass:
  num=10


ob1=MyClass()
print(ob1.num)

In [ ]:
class MyClass:
  num=10


print(MyClass.num)

In [ ]:
class MyClass:
  num=10

MyClass.num=3000
print(MyClass.num)

In [ ]:
class MyClass:
  def show(self):
    print("hy")


x=MyClass()
x.show()




In [ ]:
class MyClass:
  def show(self):
    print("hy")


MyClass.show(x)




In [ ]:
class MyClass:
  def show(self):
    print("hy")

x=MyClass()
MyClass.show(x)





In [ ]:
class  MyClass:
  def show(self):
    self.name="gauri"


print(MyClass.show(x))


AttributeError: ignored

In [ ]:
class MyClass:
  def show(self):
    print("hello")
    self.name="gauri"


MyClass.show(x)


hello


AttributeError: ignored

In [ ]:
class MyClass:
  def show(self):
    print("hello")
    self.name="how are you"

n1=MyClass()
n1.show()
print(n1.name)



hello
how are you


In [ ]:
class Student:
  def info(self):
    self.name="gauri"
    self.rollnumber="20016"


ob=Student()
ob.info()
print(ob.name)
# print(Student.info(x))
# ob=Student()
# ob.info()

gauri


In [ ]:
class Student:
  def info(self):
    self.name="gauri"
    self.rollnumber="20016"



print(Student.info(x))
ob=Student()
ob.info()
print(ob.name)
print(ob.rollnumber)


AttributeError: ignored

In [ ]:
class Home:
  room = 3
  kitchen= 1
  hall = 2



h1=Home()
h2=Home()

print(h1.room)
print(h1.kitchen)
print(h1.hall)


print(h1.room)
print(h1.kitchen)
print(h1.hall)

3
1
2
3
1
2


In [ ]:
class Home:
  room = 3
  kitchen= 1
  hall = 2



h1=Home()
h2=Home()

h1.room = 5
print(h1.room)

print(h2.room)

5
3


In [ ]:
class Home:
  room = 3
  kitchen= 1
  hall = 2


print(Home.room)


In [ ]:
class Home:
  room = 3
  kitchen = 1
  hall = 2

  def show(self):
    print("hy")


# print(Home.room)

Home.show(x)

In [ ]:
class Home:
  room = 3
  kitchen = 1
  hall = 2

  def show(self):
    print("hello")

print(Home.room)
Home.show(x)   #when print it will return none




In [ ]:
class MyClass:
  num = 100



ob1=MyClass()
ob2=MyClass()

print(MyClass.num)
print(ob1.num)
print(ob2.num)


MyClass.num =2000
print(ob1.num)
print(MyClass.num)

In [ ]:
class MyClass:
  num=100


ob1=MyClass()
ob1.area=10   #manipulation
print(ob1.area)

In [ ]:
word="gauri"
print(*word)

In [ ]:
x=6
y=2
print(x/y)
x=6
y=2
print(x//y)

In [ ]:
#python inheritance

#single inheritance


class Parent():
  def parentA(self):
    return("Parent A")

class Child(Parent):
  def childA(self):
    print("Child a")


obj=Child()
obj.childA()
obj.parentA()

# print(Parent.parentA(obj))

In [ ]:
class Parent:
  def parentA(self):
    print("Parent A")

class Child(Parent):
  def childA(self):
    print("Child a")


obj=Child()
obj.childA()
obj.parentA()

Child a
Parent A


In [ ]:
class TeacherCS:
  def cse(self):
    print("these are cse faculty")

class TeacherCivil(TeacherCS):
  def civil(self):
    print(" this is civil faculty")


class TeacherBoth(TeacherCivil):
  def both(self):
    print("can teach both")



ob=TeacherBoth()
ob.both()
ob.civil()
ob.cse()

In [ ]:
class TeacherCS:
  def cse(self):
    print("these are cse faculty")

class TeacherCivil():
  def civil(self):
    print(" this is civil faculty")


class TeacherBoth(TeacherCivil,TeacherCS):
  def both(self):
    print("can teach both")



ob=TeacherBoth()
ob.both()
ob.civil()
ob.cse()

In [ ]:
class A:
    def __init__(self):
        self.a = 1
        self.b = 2
        self.c = 3
    def seta(self):
        def afunction():
            self.a = 4
        afunction()
    def geta(self):
        return self.a


ob=A()
print(A.seta.afunction())




In [ ]:
#laptop program

class Camera:
  def __init__(self,sensor,megapixel):




class Keyboard:
  def __init__(self,keys,lights):


class Screen:
  def __init__(self,size,resolution,type):




class Laptop:
  def __init__(self,name):

  def __init__(name,Camera,Keyboard,):


In [ ]:
class Student:

    def __init__(self, id):
        self._id = id

    def registration_number(self, department_id) -> str:
        return str(self._id) + '-' + department_id


class Department:

    def __init__(self, id, student):
        self._id = id
        self._student = student

    def student_registration(self):
        return self._student.registration_number(self._id)


if __name__ == '__main__':
    student = Student(10)
    department = Department('ENG', student)
    print(department.student_registration())

**june 9 2023**

In [ ]:
class MyClass:
  num=10
  def show(self):
    self.name="gauri"


print(MyClass.num)
obj1=MyClass()
print(obj1.show())
print(obj1.name)


In [ ]:
class MyClass:
  def __init__(self,num , name):
    self.name=name
    self.num=num


obj1=MyClass(5,"gauri")
obj1.name
# obj1.num


In [ ]:
class MyClass:
  def __init__(self,num , name):
    self.name=name
    self.num=num


obj1=MyClass(5,"gauri")
print(obj1.name)

In [ ]:
#constructor vs method

class MyClass:
  def __init__(self):
    print("gauri")


o1=MyClass()
o1.__init__()

In [ ]:
class MyClass:
  def __init__(self):
    return "gauri"


o1= MyClass()
o1.__init__()

TypeError: ignored

In [ ]:
class MyClass:
  def __init__(self):
    print("hy how are you")
    # return None

o1=MyClass()

In [ ]:
class MyClass:
  def __init__(self):
    print("hy how are you")
    # return None

o1=MyClass()

In [ ]:
class MyClass:
  def __init__(self,num):
    self.num=num

  def __repr__(self):
    return str(self.num)


m1 = MyClass(10)
print(m1)
print(m1.__str__())

TypeError: ignored

In [ ]:
class MyClass:
  pass


obj1=MyClass()
print(type(MyClass))

In [ ]:
class MyClass:
  def __init__(self , num , name):
    num2=num
    name2=name
    print(num2)
    print(name2)

obj1 = MyClass(7,"gk")
# print(obj1.num2)


7
gk


In [ ]:
class MyClass:
  def __init__(self , num , name):
    self.num=num
    self.name=name


ob=MyClass(4,"hk")
print(ob.num)
print(ob.name)

4
hk


In [ ]:
class Camera:
  def __init__(self,sensor,mp):
    self.sensor=sensor
    self.mp=mp

class Keyboard:
  def __init__(self,keys,light):
    self.keys=keys
    self.light=light

class Screen:
  def __init__(self,size,resolution,stype):
    self.size =size
    self.resolution = resolution
    self.stype=stype




class Laptop:
  logo_name ="lenovo"
  def __init__(self,name,camera,keyboard,screen):
    self.name=name
    self.camera=camera
    self.keyboard=keyboard
    self.screen=screen


  def __str__(self):
    return f"Model:{self.name},\n \t Camera :(sensor:{self.camera.sensor} , mp:{self.camera.mp}),\n\t Keyboard:(keys:{self.keyboard.keys},light:{self.keyboard.light}),\n\t Screen:(size:{self.screen.size},Res:{self.screen.resolution},Type: {self.screen.stype})"


camera1 =Camera("Soby","48")
keyboard1=Keyboard("mechanical","rgbb")
screen1=Screen("26inch","600x400","led")


laptop1 = Laptop("ROG",camera1,keyboard1,screen1)
print(laptop1)


Model:ROG,
 	 Camera :(sensor:Soby , mp:48),
	 Keyboard:(keys:mechanical,light:rgbb),
	 Screen:(size:26inch,Res:600x400,Type: led)


In [ ]:
class MyClass:
  def display(self):
    self.name="gauri"
    self.age=20


ob=MyClass()
ob.display()
ob.name
ob.age

20

In [ ]:
class MyClass:
  def __init__(self, num , age):
    self.num=num
    self.age=age

obj1=MyClass(3,4)
print(obj1.num)
print(obj1.age)

3
4


In [ ]:
class MyClass:
  def __init__(self,name,age):
    self.name=name
    self.age=age


ob=MyClass("gauri",20)
print(ob.name)
print(ob.age)

gauri
20


In [ ]:
class MyClass:
  def __init__(self,age):
    self.age = age
    if age >=18:
      # self.age=18
      print("valid")
    else:
      self.age=0
      print("not")


ob=MyClass(int(input()))
(ob.age)




5
not


0

**10 june 2023**

In [ ]:
#encapsulation


class MyClass:
  __name="gauri"

  def __private_method(self):
    print("private")


obj=MyClass()






In [ ]:
class MyClass:
  def __init__(self,name,age):
    self.__name =name
    self.__age=age

  def pvt(self):
    print(self.__name , self.__age)


obj=MyClass("ITM",22)
# obj.__init__("itm ", 22)
# print(obj.__name)
obj.pvt()


ITM 22


In [ ]:
class MyClass:
  def __init__(self , name , age):
    self.__name=name
    self.age=age

  def pvt(self):
    return self.__name , self.age

obj=MyClass("itm ",  23)
obj.pvt()
name,age=obj.pvt()
print(name)
print(age)

itm 
23


In [ ]:
class MyClass:
  def __init__(self , name = None , age = 0):
    self.__name = name
    self.__age=age

  def set_name(self,name):
    self.__name=name

  def get_name(self):
    return self.__name


  def set_age(self , age):
    self.__age=age

  def get_age(self):
    return self.__age

obj=MyClass()
obj.set_name("ITM")
print(obj.get_name())
obj.set_age(22)
print(obj.get_age())





ITM
22


In [ ]:
#abstraction
from abc import ABC , abstractmethod

class Bike(ABC):
  @abstractmethod
  def show(self):
    pass

  def defined_method(self):
    print("hello")

  name="itm"

# b1=Bike()
# b1.show()

class Child(Bike):
  def show(self):
    print("implemented")

  color="blacck"

ch=Child()
ch.show()
ch.defined_method()
print(ch.name)
print(ch.color)

implemented
hello
itm
blacck


In [ ]:
#practice

class ITM:
  def __init__(self,course,fees):
    self.course=course
    self.__fees=fees


i=ITM("btech",1000)
print(i.course)
print(i.__fees)






btech


AttributeError: ignored

In [ ]:
class ITM:
  def __init__(self , course=None , fees=0 ):
    self.__course=course
    self.__fees= fees

  def set_course(self,course):
    self.__course=course

  def get_course(self):
    return self.__course

  def set_fees(self,fees):
    self.__fees=fees

  def get_fees(self):
    return self.__fees


ob=ITM()
ob.set_course()
print(ob.get_course())
#
ob.set_fees()
print(ob.get_fees())

KeyboardInterrupt: ignored

In [ ]:
class ITM:
  def __init__(self , course=None , fees=0 ):
    self.__course=course
    self.__fees= fees

  def set_course(self,course):
    self.__course=course

  def get_course(self):
    return self.__course

  def set_fees(self,fees):
    self.__fees=fees

  def get_fees(self):
    return self.__fees


ob=ITM()
ob.set_course("btech")
print(ob.get_course())
ob.set_fees(2000000)
print(ob.get_fees())

btech
2000000


In [ ]:
#astract
from abc import ABC , abstractmethod

class Animal:
  def sleep(self):
    print("going to sleep")

  @abstractmethod
  def sound(self):
    print("defines sound")
    pass

class Snake:
  def sound(self):
    print("i hissss")



ob=Animal()
ob.sleep()
ob.sound()
ob=Snake()
ob.sound()


going to sleep
defines sound
i hissss


In [ ]:
class Student:
  def __init__(self,name=None,idd= 0):
    self.__name=name
    self.__idd=idd


  def set_name(self,name):
    self.__name=name

  def get_name(self):
    return self.__name

  def set_idd(self,idd):
    self.__idd=idd

  def get_idd(self):
    return self.__idd


ob=Student()
ob.set_name("gauri")
print(ob.get_name())
ob.set_idd(22)
print(ob.get_idd())


gauri
22


In [ ]:
from abc import ABC , abstractmethod
class ITM:
  def student(self):
    print("I am an ITMIAN")

  @abstractmethod
  def btech(self):
    print("i am btech student")


class Cse:
  def btech(self):
    print("i am cse student")

class Civil:
  def btech(self):
    print("i am i")


ob=ITM()
ob.student()
ob.btech()
ob=Cse()
ob.btech(

)


I am an ITMIAN
i am btech student
i am cse student
i am in civil


**12 june 2023**

In [ ]:
#inheritance single

class Parent:
  def parent(self):
    print("parent class")

class Child(Parent):
  def child(self):
    print("cchild ")


ch = Child()
# ch.parent()
ch.child()
ch.parent()



cchild 
parent class


In [ ]:
class Gparent1:
  def gparent1(self):
    print("grandmom") #hybrid

class Gparent2:
  def gparent2(self):
    print("grandpapa")


class Son(Gparent1 , Gparent2):
  def son(self):
    print("mere papa")


class Grandson(Son):
  def grandson(self):
    print("i am child")



ch=Grandson()
ch.grandson()
ch.son()
ch.gparent1()
ch.gparent2()


i am child
mere papa
grandmom
grandpapa


In [ ]:
#multilevel
class GGparent:
  def ggparent(self):
    print("greatgrandfather") #hybrid

class Gparent(GGparent):
  def gparent(self):
    print("grandpapa")


class Son(Gparent):
  def son(self):
    print("mere papa")


class Grandson(Son):
  def grandson(self):
    print("i am child")



ch=Grandson()
ch.grandson()
ch.son()
ch.ggparent()
ch.gparent()


i am child
mere papa
greatgrandfather
grandpapa


In [ ]:
#hybrid



In [ ]:
class parent:
  def parent(self):
    print("papa")


class Son1(parent):
  def son(self):
    print("bada beta")

class Son2(parent):
  def son2(parent):
    print("chota beta")


ch=Son2()
ch.son2()

ch1=Son1()
ch1.son()

ch.parent()



chota beta
bada beta
papa


In [ ]:
#multiple

class parent1:
  def parent1(self):
    print("mom")


class parent2:
  def parent2(self):
    print("papa")


class Son1(parent1,parent2):
  def son(self):
    print("bada beta")

class Son2(parent2,parent1):
  def son2(self):
    print("chota beta")



ch=Son2()
ch.son2()
ch.parent1()
ch.parent2()

ch=Son1()
ch.son()
ch.parent1()
ch.parent2()


chota beta
mom
papa
bada beta
mom
papa


In [ ]:
class Parent:
  def __init__(self):
    print("this is parent")


class Child(Parent):
  def __init__(self):
    super().__init__()
    print("child method")


ch=Child()


this is parent
child method


In [ ]:
class Parent:
  def __init__(self):
    print("parent")

class Child(Parent):
  def __init__(self):
    super().__init__()
    print("child")
    super().__init__()


ch=Child()

parent
child
parent


In [ ]:
class Parent:
  def __init__(self , surname):
    self.surname=surname
    print("parent method")

class Child(Parent):
  def __init__(self):
    super().__init__("kothekar")
    print("child")

ch=Child()
print(ch.surname)

parent method
child
kothekar


In [ ]:
class Parent:
  def __init__(self):
    self.surname="kothekar"

  def show(self , age):
    print("this is parent method")

class Child(Parent):
  def child(self):
    print("this is child")
    super().show(22)
    print(self.surname)

ch=Child()
ch.child()

this is child
this is parent method
kothekar


In [ ]:
#multiple inheritance
class Parent1:
  def method(self):
    print("method 1")

class Parent2:
  def method(self):
    print("method 2")

class Child(Parent1,Parent2):
  print("child")


ch=Child()
ch.method()



child
method 1


In [ ]:
#multiple inheritance
class Parent1:
  def method(self):
    print("method 1")

class Parent2:
  def method(self):
    print("method 2")

class Child(Parent2,Parent1):
  print("child")


ch=Child()
ch.method()



child
method 2


In [ ]:
class Parent1:
  def __init__(self):
    print("1")

class Parent2:
  def __init__(self):
    print("2")

class Child(Parent1,Parent2):
  def __init__(self):
    super().__init__()
    print("child")

ch=Child()





1
child


In [ ]:
class Parent1:
  def __init__(self):
    print("1")


class Parent2:
  def __init__(self):
    print("2")

class Child(Parent1,Parent2):
  def __init__(self):
    Parent1().__init__()
    print("child")

ch=Child()

1
1
child


In [ ]:
#polymorphism

#--1--method overriding
#--2--method overloading
#---3--operator


In [ ]:
class Parent:
  def method(self):
    print("parent")



class Child(Parent):
  def method1(self):
    print("child")


ch=Child()
ch.method()


parent


In [ ]:
class Parent:
  def method(self):
    print("parent")



class Child(Parent):
  def method(self , num1):
    print("child")


ch=Child()
ch.method()
ch.method(10)


TypeError: ignored

In [ ]:
#method overloading change parammeters but reside within the class

class MyClass:
  def method(self,num1 ):
    print("this is method one")

  def method(self , num1 , num2):
    print("this is mothod two")

m=MyClass()
m.method(100)
m.method(100,200)

TypeError: ignored

In [ ]:
#operator overloading


class MyClass:
  def __init__(self , num):
    self.num=num

  def __add__(self ,other):
    return self.num+other.num

  def __mul__(self , other):
    return self.num * other.num

  def __sub__(self , other):
    return self.num - other.num

  def __div__(self , other):
    return self.num / other.num

  def __lt__(self , other):
    return self.num < other.num

  def __pow__(self , other):
    return self.num ** other.num

  def __floordiv__(self , other):
    return self.num // other.num

m1=MyClass(10)
m2=MyClass(20)
# print(m1.num+m2.num)
# print(m1.num*m2.num)
# print(m1.num-m2.num)
# print(m1.num/m2.num)
print(m1+m2)
print(m1*m2)
print(m1<m2)
print(m1**m2)
print(m1//m2)





30
200
True
100000000000000000000
0


In [ ]:


class MyClass:
  def __init__(self , num , num2):
    self.num=num
    self.num2=num2

  def __add__(self ,other,other1):
    return self.num+self.num

  def __mul__(self , other , other1):
    return self.num * self.num

  def __sub__(self , other , other1):
    return self.num - self.num

  def __div__(self , other , other1):
    return self.num / self.num

  def __lt__(sel)


m1=MyClass(100)
m2=MyClass(200)
m3=MyClass(100)
# print(m1.nu)
# print(m1.num*m2.num*m3.num)
# print(m1.num-m2.num-m3.num)
# print(m1.num/m2.num/m3.num)
print(m1+m2+m3)

TypeError: ignored

In [ ]:
#duck type
class Alien:
  def fly(self):
    print("this is an alien")

class Human:
  def overthinker(self):
    print("this is human")

class Animal:
  def eat(self):
    print("this is an animal")


dog = Animal()
jadu = Alien()
manav =  Human()


def checkk(sel):
  sel.eat()
  sel.fly()
  sel.overthinker()


checkk(dog)
# checkk(jadu)
# checkk(manav)





this is an animal


AttributeError: ignored

**13 june 2023**

In [ ]:
# #exception handling
# try----yha error ati he
# except ----- yha us error ko solve krte he
# finally----ye data resource ko end karne k lie use krt he

# exception is also a part of error but we do not handle the errors but we handle the exceptions

# there can be multi try multi catch.
# only single finally


#it can be try except and else  and try else:


In [ ]:
print("start")
try:
  print(10/2)
except Exception as e:
  print(e)

start
5.0


In [ ]:
print("start")
try:
  print(10/0)
except ArithmeticError as e:
  print(e)

start
division by zero


In [ ]:
print("gauri kothekar")

try:
  x=int(input())
  print(100/x)


except Exception as e:
  print("there is some errror")


finally:
  print("ennd")

gauri kothekar
0
there is some errror
ennd


In [ ]:
print("hy")

try:
  li=[1,2,3,4]
  print(li[7])

except Exception as e:
  print(e)

hy
list index out of range


In [ ]:
print("start")

try:
  tup=(8,5,6,7,8,9)
  print(tup[10])


except ArithmeticError as e:
  print(e)

start


IndexError: ignored

In [ ]:
print("start")

try:
  tup=(8,5,6,7,8,9)
  print(tup[10])


except IndexError as e:
  print(e)

start
tuple index out of range


In [ ]:
#multi except

try:
  print(10/0)

except Exception as e:
  print(e)

except ArithmeticError as e:
  print(e)

division by zero


In [ ]:
#multi except  #ese nhi likhna hota he kuki exception sare exception which are actually not to be .

try:
  print(10/0)

except Exception as e:
  print(e)

except ArithmeticError as e:
  print(e)

division by zero


In [ ]:
#multi except

try:
  print(10/0)

except ArithmeticError as e:
  print(e)

except Exception as e:
  print(e)

except ArithmeticError as e:
  print(e)

division by zero


In [ ]:
#multi try

try:
  print(10/2) #jab isme error he to vo direct iske exception me jyga but jb ism error nhi to vo uske andr jyga
  try:
    print(10/5)
  except ArithmeticError as e:
    print(e)

except ArithmeticError as e:
  print(e)

5.0
2.0


In [ ]:
#multi try

try:
  print(10/2) #jab isme error he to vo direct iske exception me jyga but jb ism error nhi to vo uske andr jyga
  try:
    print(10/0)
  except ArithmeticError as e:
    print(e)

except ArithmeticError as e:
  print(e)


5.0
division by zero


In [ ]:
#multi try

try:
  print(10/0) #jab isme error he to vo direct iske exception me jyga but jb ism error nhi to vo uske andr jyga
  try:
    print(10/0)
  except ArithmeticError as e:
    print(e)

except ArithmeticError as e:
  print(e)


division by zero


In [ ]:
#multi try

try:
  print(10/0) #jab isme error he to vo direct iske exception me jyga but jb ism error nhi to vo uske andr jyga
  try:
    print(10/2)
  except ArithmeticError as e:
    print(e)

except ArithmeticError as e:
  print(e)


division by zero


In [ ]:
try:
  try:
    print(10/0)
    li=[1,2,3,4]
    print(li[5])

  except Exception as e:
    print(e)
    # li=[1,2,3,4]
    # print(li[5])

except Exception as e:
  print(e)

division by zero


In [ ]:
try:
  try:
    print(10/0)

  except Exception as e:
    print(e)
    li=[1,2,3,4]
    print(li[5])

except Exception as e:
  print(e)

division by zero
list index out of range


In [ ]:
#finally block  isme pehle finally call hoga fir error ayga

try:
  print(10/0)

finally:
  print("ho gaya")

print("end")

ho gaya


ZeroDivisionError: ignored

In [ ]:
try:
  print(10/0)

except ZeroDivisionError as e:
  print(e)


division by zero


In [ ]:
#custom exception

#use raise keyword to throw the custom or user defined exception

x=int(input("enter the marks"))
try:
  if x>10:
    print("you are pass")
  else:
    raise ArithmeticError("You are fail")
finally:
  print("good luck")



enter the marks20
you are pass
good luck


In [ ]:
class InvalidAgeException(Exception):
  pass

try:
  x=int(input("enter your age"))
  if x<18:
    raise InvalidAgeException
  else:
    print("you are eligible")

except InvalidAgeException:
  print("invalid age")

enter your age17
invalid age


In [ ]:
class Error(BaseException):
  def __init__(self , msg):
    print(msg)

marks = int(input("enter marks"))
if marks<50:
  raise Error("fail")

else:
  print("fail")






enter marks20
fail


Error: ignored

In [ ]:
class Error(BaseException):
  def __init__(self,msg):
    self.msg=msg
    print(self.msg)

marks = int(input("enter marks"))
if marks<50:
  raise Error("fail")

else:
  print("fail")

enter marks20
fail


Error: ignored

In [ ]:
class Error(BaseException):
  def __init__(self,msg):
    self.msg=msg
    super().__init__(msg)

marks = int(input("enter marks"))
if marks<50:
  raise Error("fail")

else:
  print("pass")

enter marks60
pass


In [ ]:
class InvalidSalary(BaseException):
  def __init__(self , salary , msg="salary is not in range of(5000 , 15000)"):
    self.salary=salary
    self.msg = msg
    super().__init__(self.msg)


salary = int(input("enter"))
if not 5000<salary < 15000:
  raise InvalidSalary(salary)

enter2000


InvalidSalary: ignored

In [ ]:
class StudentFailError(BaseException):
  def __init__(self,marks, result="fail"):
    self.marks=marks
    self.result=result
    super().__init__(self.result)


m=int(input("enter the marks"))
if m<33:
  raise StudentFailError(marks)

else:
  print("you are pass !!!!")

enter the marks35
you are pass !!!!


In [ ]:
class OuterClass:
  num=10

  class InnerClass:
    def __init__(self):
      self.OuterClass.num
      print("this is inner")

ob=OuterClass()
# ob.num
# ob1=InnerClass()
# ob1.inner()

In [ ]:
class Outer(object):
  num=120


  class Inner(object):
    @staticmethod
    def get_num(cls):
      return Outer.num

  Inner.num2=num

In [ ]:
class Outer(object):
    def __init__(self):
        self.a = 111

print(f"Outer.a = {Outer().a}")

Outer.a = 111


In [ ]:
class Outer(object):
    a = 1

    class Inner(object):
        a = 2

        @classmethod
        def fun(cls):
          return Outer.a

print(Outer.Inner.fun())

1


In [ ]:
class Car(object):
  car=10
  print("this is the sedan car")

  class Engine(object):
    print("Engine is mandatory")

    @classmethod
    def engine(cls):
      return Car.car

print(Car.Engine.engine())

this is the sedan car
Engine is mandatory
10


In [ ]:
class Outer:
  var=15
  class Inner:
    def access(self):
      return Outer.var

print(Outer.Inner.access(15))

15


**14 june 2023**

In [ ]:
#file handling
f=open("PythonFh.txt","r")
f.close()

In [ ]:
#file handling
f=open("PythonFh.txt","w")
f.write("my name is gaurik ") #it overwrites the data
f.close()

In [ ]:
#file handling
f=open("PythonFh.txt","a")
f.write("i am in final year")  #adds the data
f.close()

In [ ]:
#file handling
f=open("Python.txt","a")
f.write("i am an engineer")
f.close()

In [ ]:
#file handling
f=open("Python.txt","a")
f.write("i am an engineer")
f.close()

In [ ]:
#file handling
f=open("Python.txt","r")
# f.write("i am an engineer")
print(f.read(10))
f.close()

i am an en


In [ ]:
#file handling
f=open("Python.txt","r")
print(f.readline(5))
f.close()

i am 


In [ ]:
#file handling
f=open("PythonFh.txt","r")
print(f.readlines(5))
f.close()

['my name is gaurik \n']


In [ ]:
#file handling
f=open("Python.txt","r")
for x in f:
  print(x)
f.close()

i am an engineeri am an engineeri am an engineeri am an engineeri am an engineer


In [ ]:
#dump---->write
#load----> read

li=[1,2,3,4,5]
f1=open("Python.txt", "wb")
print(f1)
print(type(f1))
print(id(f1))
import pickle
pickle.dump(li,f1)          #serialization ---> object is converted to byte
f1.close()
f1=open("Python.txt","rb")   #deserialization ---> vice versa
pickle.load(f1)
print(f1)
print(type(f1))
print(id(f1))
f1.close()


<_io.BufferedWriter name='Python.txt'>
<class '_io.BufferedWriter'>
140027618287232
<_io.BufferedReader name='Python.txt'>
<class '_io.BufferedReader'>
140027799272464


In [ ]:
with open("PythonFh.txt","r") as f1 , open("Python.txt","w") as f2:  #data is copied but with overwritten
  f2.write(f1.read())
  print(id("Python.txt"))
  print(id("PythonFh.txt"))
  f1.seek(2)
  print(f1.tell())
  print(f1.readline())

140026497838640
140026497882032
2
 name is gaurik i am in final year


In [ ]:
try:
  print("open file")
  f1 = open("PythonFh.txt","r")
  print(10/0)
  print("read file")
  print(f1.read())

except Exception as e:
  print(e)   ??

finally:
  f1.close()
  print("close file")



open file
division by zero
close file


In [ ]:
class Student:
  def __init__(self,name,age):
    self.name=name
    self.age=age


  def __str__(self):
    return self.name +str(self.age)


s1=Student("gauri",20)
s2=Student("gk",21)
s3=Student("gkkki",22)


f1=open("PythonFh.txt","wb")
import pickle
pickle.dump(s1,f1)
pickle.dump(s2,f1)
pickle.dump(s3,f1)
f1.close()

f1=open("PythonFh.txt","rb")
print(pickle.load(f1))
print(pickle.load(f1))
print(pickle.load(f1))


gauri20
gk21
gkkki22


In [ ]:
class Methods:
  name="pawan"

  def instance_method(self):
    print("this is instance method")

  def static_method()

In [ ]:
#revers a string
def reverse(str):
  str1=""
  for i in str:
    str1=i+str1
  return str1


# str="gauri"
# print(str)
# print(reverse(str))
print(reverse("gauri"))

iruag


In [ ]:
str1="gauri"
str2=str1.reverse()
print(str2)

AttributeError: ignored

In [ ]:
#convrt list to string

lis=["gauri","kothkar","22"]
string = "".join(lis)
print(string)
print(type(string))

gaurikothkar22
<class 'str'>


In [ ]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
# a=set(l1)
# b=set(l2)
# if a==b:
#   print("yes")
# else:
#   print("NO")

# x=l1.sort()
# y=l2.sort()
# print(x)
# print(y)
x=sorted(l1)
print(x)
y=sorted(l2)
print(y)

[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]


In [ ]:
#int to string
x=50
print(type(x))
print(x)
y=str(x)
print(type(y))
print(y)

<class 'int'>
50


TypeError: ignored

In [ ]:
n = 25
# check  and print type of num variable
print(type(n))
print(n)

# convert the num into string
con_num = str(n)

# check  and print type converted_num variable
print(type(con_num))
print(con_num)

<class 'int'>
25


TypeError: ignored

**15 june 2023**

In [ ]:
#multithreading
from threading import Thread
class MyThread(Thread):
  def run(self):
    for i in range(0,50):
      print(i)

th=MyThread()
th.start()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [ ]:
from threading import Thread

class MyClass(Thread):
  def run(self):
    for i in range (0 ,40):
       print("gauri")

if __name__== "__main__":

  th1=MyClass()
  th1.start()

  th2=MyClass()
  th2.start()

gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri


In [ ]:
from threading import Thread
class MyClass1(Thread):
  def run(self):
    for i in range(0,29):
      print("gauri")


class MyClass2(Thread):
  def run(self):
    for i in range(0,9):
      print("kothekar")



th1=MyClass1()
th1.start()
th2=MyClass2()
th2.start()

gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
kothekar
kothekar
kothekar
kothekar
kothekar
kothekar
kothekar
kothekar
kothekar


In [ ]:
#without class
from threading import Thread

def show():
  for i in range(0 , 10):
    print(i)

def show2():
  for i in range(0,19):
    print(i)

if __name__ == "__main__":

  t1=Thread(target = show)
  t1.start()
  t2=Thread(target=show2)
  t2.start()

0
1
2
3
4
5
60
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

7
8
9


In [ ]:
from time import sleep
# from threading import Thread

def show():
  for count in range(0,15):
    # print("gauri")
    try:
      sleep(1)
      print("gauri")
    except Exception as e:
      print(e)

if __name__ == "__main__":
  th1=Thread(target=show)
  th1.start()

In [ ]:

import threading
import time
def say_Hi():
  for i in range(3):
    time.sleep(1)
    print("hy")

def say_Apoyo():
  for i in range(3):
    time.sleep(2)
    print("Apoyo")


t1 = threading.Thread(target=say_Hi)
t2 = threading.Thread(target=say_Apoyo)
t1.start()
t2.start()



In [ ]:
from threading import Thread

class Myclass(Thread):
  def show1(self):
    for i in range(0,20):
      print(i)

  def show2(self):
    for j in range(0,10):
      print(i)

if __name__ == "__main__" :
  t=Thread(target = show)
  t.start()
  t.join()
  t2=Thread(target=show1)
  t2.start()



gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri
gauri


NameError: ignored

In [ ]:

import time
import threading

def thread_1(i):
    time.sleep(2)
    print('Value by Thread 1:', i)

def thread_2(i):
    time.sleep(5)
    print('Value by Thread 2:', i)

def thread_3(i):
    print('Value by Thread 3:', i)


# Creating three sample threads
thread1 = threading.Thread(target=thread_1, args=(1,))
thread2 = threading.Thread(target=thread_2, args=(2,))
thread3 = threading.Thread(target=thread_3, args=(3,))

# Running three thread object
thread1.start()
thread1.join()
thread2.start()
thread2.join()
thread3.start()
thread3.join()

print()
# Creating another 3 threads
thread4 = threading.Thread(target=thread_1, args=(1,))
thread5 = threading.Thread(target=thread_2, args=(2,))
thread6 = threading.Thread(target=thread_3, args=(3,))

thread4.start()
thread5.start()
thread6.start()
thread4.join()
thread5.join()
thread6.join()

Value by Thread 1: 1
Value by Thread 2: 2
Value by Thread 3: 3

Value by Thread 3: 3
Value by Thread 1: 1
Value by Thread 2: 2


In [ ]:
class TV:
  def Sony(self , name , l1):
    print("first ",name)
    l1.acquire()
    for count in range(1,100):
      print(name)
      l1.release()
      print("out first0" , name)


class Person1:
  def __init__(self, tv,name,l1):
    super().__init__()
    self.tv=tv
    self.name=name
    self.l1=l1

  def run(self):
    self.tv.sony(self.name , self.l1)


class Person2:
  def __init__(self,tv,name,l1):
     super().__init__()
     self.tv=tv
     self.name=name
     self.l1=l1

  def run(self):
    self.tv.sony(self.name ,self.l1)


if __name__ == "__main__":
  tv =TV()
  l1=Lock()
  p1=Person1(tv , "gauri",l1)
  p2=Person2(tv , "gaurik",l1)
  p1.start()
  p2.start()


NameError: ignored

**16 JUNE 2023**

In [ ]:
#unit testing

assert sum([2,3,5]) == 10 , "should be `10"

In [ ]:
def test_sum():
  assert sum([2,3,5]) == 10 , "it should be 10"

if __name__ == "__main__":
  test_sum()
  print("everything")

everything


In [ ]:
def test_sum():
  assert sum([2,3,5]) == 19, "it should be 10"

if __name__ == "__main__":
  test_sum()
  print("everything")

AssertionError: ignored

In [ ]:
def test_sum():
  assert sum([2,3,5]) == 10 , "it is 10"

def test_sub():
  assert min([4,2])==2,"it should be 2"

if __name__ == "__main__":
  test_sum()
  test_sub()
  print("correct")


correct


In [ ]:
import unittest
class TestingSum(unittest.TestCase):

  def test_sum(self):
    self.assertEqual(sum([2,3,5]) , 10 , "it shoyld be 10")

  def test_min(self):
    self.assertEqual(min([2,3]) ,2,"it should be 2")

if __name__ == "__main__":
  unittest.main()

E
ERROR: /root/ (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute '/root/'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)


SystemExit: ignored

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
import unittest
class TestingSum(unittest.TestCase):

    def test_sum(self):
        self.assertEqual(sum([2, 3, 5]), 10, "It should be 10")
    def test_sum_tuple(self):
        self.assertEqual(sum((1, 3, 5)), 10, "It should be 10")

if __name__ == '__main__':
    unittest.main()

E
ERROR: /root/ (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute '/root/'

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)


SystemExit: ignored

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**17 june 2023**

In [ ]:
import numpy as np

list1 = [1,2,3,4]
ar1 = np.array(list1)
print(type(ar1))
print(ar1)

<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
import numpy as np  #should have same length

list1 = [1,2,3,4]
ar1 = np.array(list1)
print(type(ar1))
print(ar1)
list2=[1,2,3,4]
ar2=np.array(list2)
print(ar1 + ar2)


<class 'numpy.ndarray'>
[1 2 3 4]
[2 4 6 8]


In [ ]:
list3=[1,2,3]
list4=[5,6,7]

ar3 =  np.array([list3,list4])
print(ar3)
print(ar3[1][0])

[[1 2 3]
 [5 6 7]]
5


In [ ]:
arZeros = np.zeros(3,dtype=int)  #by default  float
print(arZeros)

[0 0 0]


In [ ]:
arOnes = np.ones(5)  #by default  float
print(arOnes)

[1. 1. 1. 1. 1.]


In [ ]:
arOnes = np.ones(5 , dtype=int)  #by default  float
print(arOnes)

[1 1 1 1 1]


In [ ]:
arEmpty = np.empty(3)
print(arEmpty)

[1. 1. 1.]


In [ ]:
arArange = np.arange(1,25)
print(arArange)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
arReshaped = np.reshape(4,6)
print(arReshaped)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [ ]:
arArange = np.arange(1,11)
print(arArange.max())
print(arArange.min())
print(arArange.sum())
print(arArange.mean())

In [ ]:
aboutMyarray = np.arange(1,11).reshape(2,5)
print(aboutMyarray.ndim)
print(aboutMyarray.size)
print(aboutMyarray.shape)

In [ ]:
listId = [1,3,4]
checkIdArray = np.array(listId)
print(checkIdArray)
print(id(checkIdArray))
print(id(checkIdArray[0]))
print(id(checkIdArray[1]))
print(id(checkIdArray[2]))


In [ ]:
searchArray = np.arange(20,50)
print(searchArray[0:5])
print(searchArray[searchArray>30])
print(searchArray >30)

In [ ]:
#pandas.......

l1 = [1,2,3,4]
s1 = pd.Series(l1)
print(s1)

In [ ]:
dict1 - {1:100 , 2:200 , 3:300}
s2 = pd.Series(dict1)
print(s2)


In [ ]:
df1 = pd.Dataframe(l1)
print(df1)

In [ ]:
#multi objects as Series

list1 = [1,2,3,4]
list2 = [5,6,7,8]

lisMul = [list1 , list2]


sListMul = pd.Series(lisMul)
print(sListMul)






In [ ]:
#loc
#iloc

list1 = [1,2,3,4]
list2 = [5,6,7,8]

find = [list1,list2]
dffind = pd.DataFrame(find)
print(dffind)

**24 june 2023**

In [ ]:
#regular expressions

import re
x='how are you'
xy=re.search("^The.*Spain$",x)
print(xy)

None


In [ ]:
txt="the rain in spain"
x=re.findall("ra",txt)
print(x)

['ra']


In [ ]:
import re
txt = "java \n python \n java"
x=re.search(".+",txt)
print(x)

<re.Match object; span=(0, 5), match='java '>


In [ ]:
import re
txt = "java \n python \n java"
x=re.split("\s",txt)
print(x)

['java', '', '', 'python', '', '', 'java']


In [ ]:
import re
txt = "java \n python \n java"
x=re.split("\s",txt,2)
print(x)

['java', '', ' python \n java']


In [ ]:
import re
txt = "java python and advancce java"
x=re.sub("\s","9",txt)
print(x)

java9python9and9advancce9java


In [ ]:
import re
txt = "java \n python \n java"
x=re.sub("\s","gk",txt,2)
print(x)

javagkgk python 
 java


In [ ]:
import re

txt="my nme is Gauri"
x=re.search(r"\bG\w+",txt)
print(x.span())

(10, 15)


In [ ]:
import re
txt="my name is Gk"
x=re.search(r"\bG\w+",txt)
print(x.string)

my name is Gk


In [ ]:
import re

txt="my nme is Gauri"
x=re.search(r"\bG\w+",txt)
print(x.group())

Gauri
